---
mdd_tags:
  - hq_router
  - site_router
mdd_checks:
  - name: Check Network-wide Routes
    command: 'show ip route vrf internal_1'
    schema: 'pyats/show_ip_route.yml.j2'
    method: nso_parse
    check_vars:
      vrf: internal_1
      routes:
        - route: 172.16.0.0/24
        - route: 192.168.1.0/24
        - route: 192.168.2.0/24
