- name: Ping hosts
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - network-tests
  tasks:
    - include_role:
        name: network-tests
        tasks_from: ping-test
      vars:
        ping_dst_ip: "{{ item.dst_ip }}"
        # ping_src_ip: "{{ item.src_ip | default('') }}"
        ping_host: "{{ item.src_host }}"
        # ping_vpn: "{{ item.vpn }}"
        ping_pass: "{{ item.pass | default(yes) }}"
      loop: "{{ ping_tests | default([]) }}"
      ignore_errors: yes