collections:
  - name: https://github.com/model-driven-devops/ansible-mdd.git,mdd-dev
    type: git
  - name: https://github.com/model-driven-devops/ansible-nso.git
    type: git
  - name: https://github.com/CiscoDevNet/ansible-cml.git,mdd-dev
    type: git
