collections:
  - name: https://github.com/ciscodevnet/ansible-cml.git
    type: git
  - name: https://github.com/model-driven-devops/ansible-mdd.git,jk-dev
    type: git
  - name: https://github.com/model-driven-devops/ansible-nso.git
    type: git
  - name: amazon.aws
    source: https://galaxy.ansible.com
