collections:
  - name: https://github.com/ciscodevnet/ansible-cml.git
    type: git
  - name: https://github.com/model-driven-devops/ansible-mdd.git,mdd-dev
    type: git
  - name: https://github.com/model-driven-devops/ansible-nso.git
    type: git
  - name: aws.amazon
    source: https://galaxy.ansible.com
