all:
  vars:
    mdd_model_repos:
      - name: nso-oc-services
        model_list:
          - mdd
    nso_installer_file: https://colabucket.s3.amazonaws.com/sw/cisco/nso/6.1/nso-6.1.linux.x86_64.signed.bin
    nso_ned_files:
      - https://colabucket.s3.amazonaws.com/sw/cisco/nso/6.1/ncs-6.1-cisco-ios-6.92.7.signed.bin
      - https://colabucket.s3.amazonaws.com/sw/cisco/nso/6.1/ncs-6.1-cisco-nx-5.23.13.signed.bin
      - https://colabucket.s3.amazonaws.com/sw/cisco/nso/6.1/ncs-6.1-cisco-iosxr-7.49.2.signed.bin
      - https://colabucket.s3.amazonaws.com/sw/cisco/nso/6.1/ncs-6.0.3-cisco-asa-6.18.3.signed.bin
    nso_default_ned: cisco-ios-cli-6.92
    nso_package_repos:
      - name: mdd
        repo: https://github.com/model-driven-devops/nso-oc-services.git
        version: v2.70.0
        service_list:
          - mdd
  children:
    nso:
      vars:
        ansible_user: "{{ lookup('env', 'NSO_USERNAME') | default('ubuntu', true) }}"
        ansible_password: "{{ lookup('env', 'NSO_PASSWORD') | default('admin', true) }}"
        ansible_python_interpreter: /usr/bin/python3
      hosts:
        nso1:
