all:
  vars:
#    nso_installer_name: nso-5.4.2.linux.x86_64.signed.bin
#    nso_package_list:
#      - ncs-5.4.1-cisco-ios-6.68.signed.bin
#      # - ncs-5.4.1-cisco-ios-6.68.tar.gz
#      # - ncs-5.4.2-cisco-nx-5.21.1.tar.gz
  children:
    nso_hosts:
      vars:
        admin_user: ubuntu
        admin_password: admin
        nso_install_dir: /pkgs/nso-install
        nso_run_dir: /home/ubuntu/ncs-run
        nso_java_opts: "-Xmx2G -Xms1G"
        nso_devices_seed_template: "nso-deviceSetup.xml.j2"
        ansible_user: "{{ admin_user }}"
        ansible_password: "{{ admin_password }}"
        ansible_python_interpreter: "/usr/bin/python3"
      hosts:
        hq-nso1:
    nso_devices:
      vars:
        mgmt_ip: "{{ interfaces.Loopback0.ip.primary }}"
        nso_ned_id: cisco-ios-cli-6.69
      hosts:
        hq-rtr1:
        hq-rtr2:
        site1-rtr1:
        site2-rtr1:
