---
- name: Remove hq-pop NAT interfaces
  connection: local
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Delete GigabitEthernet2
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          device: hq-pop
          name: GigabitEthernet2
        state: absent
    - name: Delete GigabitEthernet2.10
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          device: hq-pop
          name: GigabitEthernet2.10
        state: absent
    - name: Delete GigabitEthernet8
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          device: hq-pop
          name: GigabitEthernet8
        state: absent
